name: Go Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19' # Specify the Go version.

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: go get -v ./...

      - name: Build binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o hey ./...

      - name: Upload Release Asset
        id: upload-release-asset
        uses: softprops/action-gh-release@v1
        with:
          files: hey
          tag_name: latest
          release_name: Latest Release
          overwrite: true
          draft: false
          prerelease: false
          body: 'This is the latest release. Please see the changelog.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
